// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistense.Data;

#nullable disable

namespace Persistense.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240430164156_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is the first novel by Jane Austen",
                            Title = "Sense and Sensibility",
                            Year = 1811
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is a novel of manners",
                            Title = "Pride and Prejudice",
                            Year = 1813
                        },
                        new
                        {
                            Id = 3,
                            Description = "The novel tells the story of Fanny Price, starting when her overburnered family sends her at the age of tento live in the household of her wealthy aunt and uncle.",
                            Title = "Mansfield Park",
                            Year = 1814
                        },
                        new
                        {
                            Id = 4,
                            Description = "This is a novel of manners.",
                            Title = "Emma",
                            Year = 1816
                        },
                        new
                        {
                            Id = 5,
                            Description = "This is a coming-of-age novel and a satire of Gothic novels.",
                            Title = "Northanger Abbey",
                            Year = 1818
                        },
                        new
                        {
                            Id = 6,
                            Description = "The story concerns Anne Elliot, an Englishwoman of 27 years, whose family moves to lower their home to an admiral and his wife.",
                            Title = "Persuasion",
                            Year = 1818
                        },
                        new
                        {
                            Id = 7,
                            Description = "This is an epistolary novella.",
                            Title = "Lady Susan",
                            Year = 1871
                        });
                });

            modelBuilder.Entity("Domain.Entities.FemaleCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Characteristic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("FemaleCharacters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Characteristic = "The sensible and reserved eldest daughter of Mr and Mrs Henry Dashwood.",
                            Name = "Elinor Dashwood"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            Characteristic = "The romantically inclined and eagerly expressive second daughter of Mr and Mrs Henry Dashwood.",
                            Name = "Marianne Dashwood"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            Characteristic = "the youngest daughter of Mr and Mrs Henry Dashwood.",
                            Name = "Margaret Dashwood"
                        });
                });

            modelBuilder.Entity("Domain.Entities.MaleCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Characteristic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("MaleCharacters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Characteristic = "The elder of Fanny Dashwood's two brothers.",
                            Name = "Edward Ferras"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            Characteristic = "A philandering nephew of a neighbour of the Middletons.",
                            Name = "John Willoughby"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            Characteristic = "a close friend of Sir John Middleton.",
                            Name = "Colonel Brandon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
